### ISSUE TITLE
can this work with fred registry?

### ISSUE THREAD

**Issue by anantsparrow** [internetee/registrar_center2#102]
will this work?

**Comment by vohmar** [comment]
with some effort it can me made to work with any registry, but it is designed for our registry platform and works over Restful-EPP API that FRED does not have. So out of the box it does not work with FRED unfortunately.

**Comment by vohmar** [comment]
https://github.com/internetee/registry has web based admin UI for most common configurations - including adding registrars, users, zones and sub-zones. Some more specific configurations that are usually done only once on setting up the registry are done in config files.
